import * as vscode from 'vscode';

/**
 * Attaches a RelatedInformation entry to a diagnostic, linking it to
 * the XSLT source location that generated the output line.
 *
 * Looks up outputLine in traceMap. If found, appends a
 * DiagnosticRelatedInformation entry to diagnostic.relatedInformation.
 * Message: "Generated by XSLT template at this location"
 *
 * No-op if traceMap does not have an entry for outputLine.
 * Never throws.
 */
export function attachRelatedInfo(
    diagnostic: vscode.Diagnostic,
    outputLine: number,
    traceMap: Map<number, vscode.Location>
): void {
    const location = traceMap.get(outputLine);
    if (!location) { return; }

    const related = new vscode.DiagnosticRelatedInformation(
        location,
        'Generated by XSLT template at this location'
    );

    if (!diagnostic.relatedInformation) {
        diagnostic.relatedInformation = [related];
    } else {
        diagnostic.relatedInformation = [...diagnostic.relatedInformation, related];
    }
}
